# Generated by Django 3.2.13 on 2022-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the pet', max_length=15)),
                ('species', models.CharField(help_text='Enter the species of the pet', max_length=10)),
                ('breed', models.CharField(help_text='Enter the breed of the pet', max_length=15)),
                ('age', models.IntegerField(help_text='Enter the age of the pet in years')),
                ('gender', models.CharField(help_text='Enter the gender of the pet', max_length=15)),
                ('description1', models.CharField(max_length=150)),
                ('description2', models.CharField(max_length=150)),
                ('description3', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
