# Generated by Django 3.2.13 on 2022-10-20 18:37

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/home/runner/The-Adoption-Center/static/images')),
        ),
    ]
