# Generated by Django 3.2.13 on 2022-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
