# Generated by Django 3.2.13 on 2022-10-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0006_pet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='url',
        ),
        migrations.AlterField(
            model_name='pet',
            name='description1',
            field=models.CharField(max_length=1500),
        ),
    ]
